[mysqld]
basedir=F:/mysql-server/mysql-8.0.46-winx64
datadir=F:/mysql-server/mysql-8.0.46-winx64/data
port=3306

character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
default_authentication_plugin=mysql_native_password

[client]
port=3306
default-character-set=utf8mb4
