CREATE TABLE `t_match_ext` (
	`cnjc_match_id` VARCHAR(200) NOT NULL COLLATE 'utf8mb4_general_ci',
	`match_num` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`league_name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`match_date` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`match_time` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`home_name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`away_name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`cnjc_flag` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '竞彩足球' COLLATE 'utf8mb4_general_ci',
	`bet_single_flag` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_general_ci',
	`is_hot` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '是否热门投注' COLLATE 'utf8mb4_general_ci',
	`business_date` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_general_ci',
	`match_id` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`bet_single_type` VARCHAR(200) NULL DEFAULT 'HAD' COMMENT 'HAD , HHAD' COLLATE 'utf8mb4_general_ci',
	`final_score` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`created_time` DATETIME NOT NULL DEFAULT (now()),
	`updated_time` DATETIME NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`cnjc_match_id`) USING BTREE,
	UNIQUE INDEX `match_id` (`match_id`) USING BTREE,
	INDEX `idx_date_bet` (`match_date` DESC, `bet_single_flag`) USING BTREE,
	INDEX `idx_cnjc_match_id` (`cnjc_match_id`) USING BTREE,
	INDEX `idx_cnjc_flag` (`cnjc_flag`) USING BTREE,
	INDEX `idx_is_hot` (`is_hot`) USING BTREE,
	INDEX `idx_business_date` (`business_date`) USING BTREE,
	INDEX `idx_cnjc_hot` (`cnjc_flag`, `is_hot`) USING BTREE,
	INDEX `idx_bet_single_type` (`bet_single_type`) USING BTREE,
	INDEX `idx_match_ext_single_flag` (`bet_single_flag`) USING BTREE,
	INDEX `idx_match_ext_cnjc_match_id` (`cnjc_match_id`) USING BTREE,
	INDEX `idx_match_ext_league_name` (`league_name`) USING BTREE,
	INDEX `idx_match_ext_cnjc_single` (`cnjc_match_id`, `bet_single_flag`) USING BTREE,
	INDEX `idx_t_match_ext_single_league` (`bet_single_flag`, `league_name`) USING BTREE,
	INDEX `idx_t_match_ext_match_id` (`match_id`) USING BTREE,
	INDEX `idx_t_match_ext_cnjc_match_id` (`cnjc_match_id`) USING BTREE,
	INDEX `idx_match_ext_single_kickoff` (`bet_single_flag`, `match_id`, `cnjc_match_id`) USING BTREE,
	INDEX `idx_bet_single_type_odds` (`bet_single_flag`, `bet_single_type`) USING BTREE,
	INDEX `idx_match_ext_date_num` (`match_date` DESC, `match_num` DESC) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `t_match` (
	`t_id` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`tn_name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`t_season` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`match_id` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_general_ci',
	`round_number` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`round_type` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`round_group` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`home_id` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`home_name` VARCHAR(200) NULL DEFAULT NULL COMMENT '数据冗余 ， 降低关联查询' COLLATE 'utf8mb4_general_ci',
	`home_name_en` VARCHAR(200) NULL DEFAULT NULL COMMENT '数据冗余 ， 降低关联查询' COLLATE 'utf8mb4_general_ci',
	`ah_main_k` VARCHAR(200) NULL DEFAULT NULL COMMENT '亚盘盘口' COLLATE 'utf8mb4_general_ci',
	`away_id` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`away_name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`away_name_en` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`kickoff_time` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`period_time` VARCHAR(200) NULL DEFAULT NULL COMMENT '比赛进行时间' COLLATE 'utf8mb4_general_ci',
	`duration_to_start` VARCHAR(200) NULL DEFAULT NULL COMMENT '距开赛时间' COLLATE 'utf8mb4_general_ci',
	`status` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`final_score` VARCHAR(20) NULL DEFAULT NULL COMMENT '比分' COLLATE 'utf8mb4_general_ci',
	`ht_score` VARCHAR(20) NULL DEFAULT NULL COMMENT '半场比分' COLLATE 'utf8mb4_general_ci',
	`full_corner` VARCHAR(20) NULL DEFAULT NULL COMMENT '角球' COLLATE 'utf8mb4_general_ci',
	`ht_corner` VARCHAR(20) NULL DEFAULT NULL COMMENT '半场角球' COLLATE 'utf8mb4_general_ci',
	`card_yellow` VARCHAR(20) NULL DEFAULT NULL COMMENT '黄牌' COLLATE 'utf8mb4_general_ci',
	`card_red` VARCHAR(20) NULL DEFAULT NULL COMMENT '红牌' COLLATE 'utf8mb4_general_ci',
	`crawler_from` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`map_500_match_id` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`map_tian_match_id` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`map_sofa_match_id` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`map_packball_match_id` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`created_time` DATETIME NULL DEFAULT (now()),
	`updated_time` DATETIME NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`map_process` INT NULL DEFAULT '0' COMMENT '0-未处理， 1-英文名done, 2-sofa done, 4-500 done, 8-titan done, 16- packball done',
	PRIMARY KEY (`match_id`) USING BTREE,
	INDEX `key_tour_round` (`t_id`, `round_number`) USING BTREE,
	INDEX `key_kickoff_time` (`kickoff_time`) USING BTREE,
	INDEX `索引 4` (`t_id`, `home_name`) USING BTREE,
	INDEX `索引 5` (`t_id`, `away_name`) USING BTREE,
	INDEX `索引 6` (`t_id`, `home_name`, `away_name`) USING BTREE,
	INDEX `索引 7` (`created_time`) USING BTREE,
	INDEX `idx_kickoff_created` (`kickoff_time`, `created_time`) USING BTREE,
	INDEX `idx_tid_home` (`t_id`, `home_name`) USING BTREE,
	INDEX `idx_tid_away` (`t_id`, `away_name`) USING BTREE,
	INDEX `idx_t_match_kickoff_time` (`kickoff_time`) USING BTREE,
	INDEX `idx_match_kickoff_type` (`kickoff_time` DESC, `match_id`) USING BTREE,
	INDEX `idx_match_kickoff_time_desc` (`kickoff_time` DESC) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `t_match_cnjc_ext` (
	`match_id` VARCHAR(50) NOT NULL COMMENT '比赛ID' COLLATE 'utf8mb4_general_ci',
	`final_goal` VARCHAR(20) NULL DEFAULT NULL COMMENT '比赛结果比分' COLLATE 'utf8mb4_general_ci',
	`home_team_ranking` INT NULL DEFAULT NULL COMMENT '主队排名',
	`away_team_ranking` INT NULL DEFAULT NULL COMMENT '客队排名',
	`bookmaker_profit_loss` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '机构盈亏金额',
	`bookmaker_profit_result` TINYINT NULL DEFAULT NULL COMMENT '机构盈亏结果：1-盈利，0-亏损',
	`created_time` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT '创建时间',
	`updated_time` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`latest_had_sequence` INT NULL DEFAULT NULL COMMENT 'HAD类型最新赔率记录sequence_order',
	`latest_hhad_sequence` INT NULL DEFAULT NULL COMMENT 'HHAD类型最新赔率记录sequence_order',
	`latest_had_odds_d` DECIMAL(10,4) NULL DEFAULT NULL COMMENT 'HAD类型最新平赔',
	`latest_hhad_odds_d` DECIMAL(10,4) NULL DEFAULT NULL COMMENT 'HHAD类型最新平赔',
	PRIMARY KEY (`match_id`) USING BTREE,
	INDEX `idx_bookmaker_result` (`bookmaker_profit_result`) USING BTREE,
	INDEX `idx_created_time` (`created_time`) USING BTREE,
	INDEX `idx_latest_had_odds_d` (`latest_had_odds_d`) USING BTREE,
	INDEX `idx_latest_hhad_odds_d` (`latest_hhad_odds_d`) USING BTREE
)
COMMENT='比赛结果排名及机构盈亏表（在500w的fastapi工程中， 提供接口查询排名）'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `t_market_support_cnjc` (
	`rec_hash` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`type` VARCHAR(100) NULL DEFAULT NULL COMMENT 'HAD 竞彩 HHAD 单关' COLLATE 'utf8mb4_general_ci',
	`cnjc_match_id` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`h_probability` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`h_supportRate` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`d_probability` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`d_supportRate` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`a_probability` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`a_supportRate` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`won` FLOAT NULL DEFAULT NULL COMMENT '投注量',
	`draw` FLOAT NULL DEFAULT NULL,
	`lose` FLOAT NULL DEFAULT NULL,
	`is_hot` VARCHAR(50) NULL DEFAULT '0' COMMENT '是否热门' COLLATE 'utf8mb4_general_ci',
	`goal_line` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`odds_h` FLOAT NULL DEFAULT NULL,
	`odds_d` FLOAT NULL DEFAULT NULL,
	`odds_a` FLOAT NULL DEFAULT NULL,
	`abs_value` FLOAT NULL DEFAULT NULL COMMENT '绝对值？',
	`e_key` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`e_number` FLOAT NULL DEFAULT NULL,
	`e_value` FLOAT NULL DEFAULT NULL,
	`result` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`match_result` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`vote_date` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`record_updated_time` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`created_time` DATETIME NULL DEFAULT (now()),
	`updated_time` DATETIME NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`is_baseline` VARCHAR(5) NULL DEFAULT '0' COMMENT '是否基准记录(最早一条)' COLLATE 'utf8mb4_general_ci',
	`won_delta` FLOAT NULL DEFAULT '0' COMMENT '主胜增量投注',
	`draw_delta` FLOAT NULL DEFAULT '0' COMMENT '平局增量投注',
	`lose_delta` FLOAT NULL DEFAULT '0' COMMENT '客胜增量投注',
	`won_profit_delta` FLOAT NULL DEFAULT '0' COMMENT '主胜增量盈亏',
	`draw_profit_delta` FLOAT NULL DEFAULT '0' COMMENT '平局增量盈亏',
	`lose_profit_delta` FLOAT NULL DEFAULT '0' COMMENT '客胜增量盈亏',
	`won_profit_cumulative` FLOAT NULL DEFAULT '0' COMMENT '主胜累计盈亏',
	`draw_profit_cumulative` FLOAT NULL DEFAULT '0' COMMENT '平局累计盈亏',
	`lose_profit_cumulative` FLOAT NULL DEFAULT '0' COMMENT '客胜累计盈亏',
	`won_cumulative_payout` FLOAT NULL DEFAULT '0' COMMENT '主胜累积赔付额：历史各期投注按当期赔率计算的累积赔付总额',
	`draw_cumulative_payout` FLOAT NULL DEFAULT '0' COMMENT '平局累积赔付额：历史各期投注按当期赔率计算的累积赔付总额',
	`lose_cumulative_payout` FLOAT NULL DEFAULT '0' COMMENT '客胜累积赔付额：历史各期投注按当期赔率计算的累积赔付总额',
	`won_payout_ratio` FLOAT NULL DEFAULT '0' COMMENT '主胜赔付比例',
	`draw_payout_ratio` FLOAT NULL DEFAULT '0' COMMENT '平局赔付比例',
	`lose_payout_ratio` FLOAT NULL DEFAULT '0' COMMENT '客胜赔付比例',
	`sequence_order` FLOAT NULL DEFAULT '0' COMMENT '时间序列顺序',
	PRIMARY KEY (`rec_hash`) USING BTREE,
	INDEX `索引 2` (`type`, `cnjc_match_id`) USING BTREE,
	INDEX `索引 3` (`cnjc_match_id`, `type`) USING BTREE,
	INDEX `idx_cnjc_created` (`cnjc_match_id`, `created_time`) USING BTREE,
	INDEX `idx_cnjc_type_created` (`cnjc_match_id`, `type`, `created_time` DESC) USING BTREE,
	INDEX `idx_cnjc_match_type_vote_date` (`cnjc_match_id`, `type`, `vote_date` DESC) USING BTREE,
	INDEX `idx_cnjc_match_type_created_time` (`cnjc_match_id`, `type`, `created_time` DESC) USING BTREE,
	INDEX `idx_cnjc_rec_hash` (`rec_hash`) USING BTREE,
	INDEX `idx_cnjc_match_id` (`cnjc_match_id`) USING BTREE,
	INDEX `idx_cnjc_vote_date` (`vote_date` DESC) USING BTREE,
	INDEX `idx_market_support_cnjc_type_created` (`type`, `created_time`) USING BTREE,
	INDEX `idx_market_support_cnjc_cnjc_match_id_type` (`cnjc_match_id`, `type`) USING BTREE,
	INDEX `idx_market_support_cnjc_profit_cumulative` (`won_profit_cumulative`, `draw_profit_cumulative`, `lose_profit_cumulative`) USING BTREE,
	INDEX `idx_market_support_cnjc_type_profit` (`type`, `won_profit_cumulative`, `draw_profit_cumulative`, `lose_profit_cumulative`) USING BTREE,
	INDEX `idx_t_market_support_cnjc_created_type` (`created_time`, `type`) USING BTREE,
	INDEX `idx_t_market_support_cnjc_cnjc_type` (`cnjc_match_id`, `type`) USING BTREE,
	INDEX `idx_t_market_support_cnjc_cnjc_type_created` (`cnjc_match_id`, `type`, `created_time`) USING BTREE,
	INDEX `idx_market_support_cnjc_created_type_cnjc` (`created_time`, `type`, `cnjc_match_id`) USING BTREE,
	INDEX `idx_market_support_cnjc_created_time` (`created_time`) USING BTREE,
	INDEX `idx_cnjc_match_type_sequence` (`cnjc_match_id`, `type`, `sequence_order` DESC) USING BTREE,
	INDEX `idx_sequence_order` (`sequence_order` DESC) USING BTREE,
	INDEX `idx_cnjc_type_profit_sequence` (`cnjc_match_id`, `type`, `won_profit_cumulative`, `draw_profit_cumulative`, `lose_profit_cumulative`, `sequence_order` DESC) USING BTREE
)
COMMENT='中国竞彩支持率和概率'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
